# Удалим строку version
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskmanagerbd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=tatiana1508

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=taskmanagerbd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tatiana1508
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: